" Calling PLUG
"
call plug#begin()


Plug 'wafelack/ark.vim'
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'

let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#formatter='unique_tail_improved'
let g:airline#extensions#disable_rtp_load=1
let g:airline_powerline_fonts=1
let NERDTreeShowHidden=1

call plug#end()

" General settings
"
set background=dark
colorscheme dracula

set guifont=DroidSansMono\ Nerd\ Font\ 11
set number relativenumber
set viminfofile=NONE
set noerrorbells
set shiftwidth=4
set smartindent
set ignorecase
set autoindent
set viminfo=""
set smartcase
set showmatch
set incsearch
set expandtab
set tabstop=4
syntax enable
filetype on
set showcmd

" Custom Keybindings
"
nnoremap <Leader>n :NERDTreeFocus<Cr>
nnoremap <C-n> :NERDTreeToggle<Cr>
nnoremap <C-f> :NERDTreeFind<Cr>
