#nord
# class                 border  backgr. text    indicator child_border
client.focused          #8fbcbb #8fbcbb #1a1826 #8fbcbb   #8fbcbb
client.focused_inactive #4c566a #4c566a #ffffff #4c566a   #4c566a
client.unfocused        #333333 #222222 #888888 #292d2e   #222222
client.urgent           #cc241d #900000 #ffffff #cc241d   #cc241d
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background       #ffffff

bar {
   colors {
            separator  #5f80af
            background #5f80af
            statusline #e5e9f0

            #                   border  background text
            focused_workspace  #5f80af #5f80af    #e5e9f0
            active_workspace   #5f80af #5f80af    #4c566a
            inactive_workspace #5f80af #5f80af    #4c566a
            urgent_workspace   #5f80af #5f80af    #ebcb8b
            binding_mode       #5f80af #5f80af    #4c566a
    }
    
    output eDP
    position top
    tray_padding 2
    tray_output eDP
    font pango:TempleOS 12
    workspace_min_width 12
    strip_workspace_numbers yes
    status_command i3status -c $i3_Dir/status_bars/eDP_tos.conf
}

bar {
   colors {
            separator  #5f80af
            background #5f80af
            statusline #e5e9f0

            #                   border  background text
            focused_workspace  #5f80af #5f80af    #e5e9f0
            active_workspace   #5f80af #5f80af    #4c566a
            inactive_workspace #5f80af #5f80af    #4c566a
            urgent_workspace   #5f80af #5f80af    #ebcb8b
            binding_mode       #5f80af #5f80af    #4c566a
    }
    
    output HDMI-A-0
    position top
    tray_output none
    font pango:TempleOS 12
    workspace_min_width 12
    strip_workspace_numbers yes
    status_command i3status -c $i3_Dir/status_bars/HDMI_tos.conf
}

